quarkus.application.name=docstream-cleanarch
quarkus.http.port=8080
quarkus.log.console.json=true
quarkus.log.level=INFO

quarkus.mongodb.connection-string = mongodb://root:root@localhost:27017
quarkus.mongodb.database = docstream
quarkus.mongodb.credentials.username = root
quarkus.mongodb.credentials.password = root
quarkus.mongodb.credentials.auth-source = admin

mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:29092

mp.messaging.outgoing.files-processed.connector=smallrye-kafka
mp.messaging.outgoing.files-processed.topic=files-processed
mp.messaging.outgoing.files-processed.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.files-processed.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.files-processed.acks=1

mp.messaging.incoming.files-in.connector=smallrye-kafka
mp.messaging.incoming.files-in.topic=files-in
mp.messaging.incoming.files-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.files-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.files-in.auto.offset.reset=earliest
mp.messaging.incoming.files-in.enable.auto.commit=true

aws.region=us-east-1
aws.s3.bucket-name=docstream-bucket
aws.access-key-id=${AWS_KEY_ID}
aws.secret-access-key=${AWS_ACCESS_KEY}

%dev.quarkus.mongodb.connection-string = mongodb://root:root@localhost:27017
%dev.quarkus.mongodb.database = docstream_dev

%dev.mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:29092

